Add method to get cached resource from syncer
submariner-io/admiral pull request #116
Opened 2020-08-31 16:31 UTC by tpantelis

See https://github.com/submariner-io/admiral/issues/115

Signed-off-by: Tom Pantelis <tompantelis@gmail.com>

2020-09-01 16:34 UTC, skitt requested changes

2020-09-01 16:34 UTC, skitt commented on pkg/syncer/resource_syncer_test.go
> +		It("should successfully the resource", func() {
```suggestion
		It("should return the resource", func() {
```

2020-09-01 16:36 UTC, tpantelis commented on pkg/syncer/resource_syncer_test.go
> +		It("should successfully the resource", func() {
yup 😄

2020-09-02 07:12 UTC, skitt approved these changes

2020-09-02 22:21 UTC, merged