Pin shipyard to 0.9.0
submariner-io/admiral pull request #215
Opened 2021-05-04 16:00 UTC by Jaanki

Signed-off-by: Janki Chhatbar <jchhatba@redhat.com>

2021-05-04 16:23 UTC, tpantelis approved these changes

2021-05-05 07:59 UTC, skitt requested changes
Minor issue: this needs `go mod tidy`.

2021-05-05 07:59 UTC, skitt commented on go.sum
>  github.com/submariner-io/shipyard v0.9.0-rc0/go.mod h1:vDGWreRLu2VfBoR8J4UgPKJjatx8pLkj89qAgB+N0ZE=
Please run `go mod tidy` as well.

2021-05-05 14:18 UTC, skitt approved these changes

2021-05-05 14:28 UTC, merged