Add subctl component name
submariner-io/admiral pull request #857
Opened 2024-02-21 15:09 UTC by maayanf24

2024-02-21 15:38 UTC, skitt requested changes
Could you explain (in the commit message) why this is needed? Do we need to deploy a `subctl` pod for `subctl gather`?

2024-02-26 12:15 UTC, maayanf24 commented
> Could you explain (in the commit message) why this is needed? Do we need to deploy a `subctl` pod for `subctl gather`?

done

2024-02-28 12:52 UTC, tpantelis approved these changes

2024-03-01 19:29 UTC, aswinsuryan approved these changes

2024-03-04 04:50 UTC, vthapar approved these changes

2024-03-04 09:10 UTC, skitt approved these changes

2024-03-04 09:10 UTC, merged